server:
  port: 8082

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/library
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


#logging:
#  level:
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.hibernate:
#      SQL: DEBUG
#      type.descriptor.sql.BasicBinder: TRACE